import { MediaItem } from '@/types/media';

export const MOCK_MEDIA_ITEMS: MediaItem[] = [
  {
    id: '1',
    title: 'Dune',
    type: 'BOOK',
    coverUrl: 'https://www.impawards.com/2021/posters/dune_ver2_xlg.jpg',
    rating: 9.5,
    status: 'COMPLETED',
    author: 'Frank Herbert',
    releaseYear: 1965,
    genres: ['Science Fiction', 'Adventure'],
    review: 'A masterpiece of science fiction. The worldbuilding is unparalleled.',
    createdAt: '2024-12-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Elden Ring',
    type: 'GAME',
    coverUrl: 'https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/phvVT0qZfcRms5qDAk0SI3CM.png',
    rating: 10,
    status: 'PLAYING',
    platform: 'PlayStation 5',
    releaseYear: 2022,
    genres: ['RPG', 'Action'],
    createdAt: '2024-12-20T14:30:00Z',
  },
  {
    id: '3',
    title: 'Oppenheimer',
    type: 'MOVIE',
    coverUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    rating: 8.8,
    status: 'COMPLETED',
    releaseYear: 2023,
    genres: ['Biography', 'Drama', 'History'],
    review: 'Christopher Nolan at his finest. Cillian Murphy delivers an Oscar-worthy performance.',
    createdAt: '2025-01-05T18:00:00Z',
  },
  {
    id: '4',
    title: 'Succession',
    type: 'SERIES',
    coverUrl: 'https://image.tmdb.org/t/p/w500/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg',
    rating: 9.2,
    status: 'COMPLETED',
    releaseYear: 2018,
    genres: ['Drama'],
    review: 'Best written show in years. The finale was perfect.',
    createdAt: '2025-01-08T20:15:00Z',
  },
  {
    id: '5',
    title: 'The Legend of Zelda: Breath of the Wild',
    type: 'GAME',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
    rating: 9.8,
    status: 'COMPLETED',
    platform: 'Nintendo Switch',
    releaseYear: 2017,
    genres: ['Action-Adventure'],
    createdAt: '2024-11-10T12:00:00Z',
  },
  {
    id: '6',
    title: 'Blade Runner 2049',
    type: 'MOVIE',
    coverUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    rating: 9.0,
    status: 'COMPLETED',
    releaseYear: 2017,
    genres: ['Science Fiction', 'Drama'],
    createdAt: '2024-12-01T16:45:00Z',
  },
  {
    id: '7',
    title: 'Interstellar',
    type: 'MOVIE',
    coverUrl: 'https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_UF894,1000_QL80_.jpg',
    rating: 8.7,
    status: 'COMPLETED',
    releaseYear: 2014,
    genres: ['Science Fiction', 'Drama'],
    review: 'Mind-bending sci-fi. The soundtrack is phenomenal.',
    createdAt: '2024-11-20T09:30:00Z',
  },
  {
    id: '8',
    title: 'The Office',
    type: 'SERIES',
    coverUrl: 'https://m.media-amazon.com/images/I/71lGhXgYIQL._AC_SY679_.jpg',
    rating: 8.9,
    status: 'WATCHING',
    releaseYear: 2005,
    genres: ['Comedy'],
    createdAt: '2025-01-09T11:00:00Z',
  },
  {
    id: '9',
    title: '1984',
    type: 'BOOK',
    coverUrl: 'https://m.media-amazon.com/images/I/71rpa1-kyvL._AC_UF1000,1000_QL80_.jpg',
    rating: 9.0,
    status: 'READING',
    author: 'George Orwell',
    releaseYear: 1949,
    genres: ['Dystopian', 'Political Fiction'],
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: '10',
    title: 'God of War Ragnarök',
    type: 'GAME',
    coverUrl: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png',
    rating: null,
    status: 'WANT_TO_PLAY',
    platform: 'PlayStation 5',
    releaseYear: 2022,
    genres: ['Action-Adventure'],
    createdAt: '2025-01-11T15:20:00Z',
  },
];
